modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="jm"
version="1.0.0"
displayName="JoJo's Blocky Adventure!"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="leon.ex, MCreator"

[[dependencies.jm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



